import type { Metadata } from "next";
// import { Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./Shared/Navbar/NavBar";
import Footer from "./Shared/Footer/Footer";
import ThemeButton from "./Shared/Theme Button/ThemeButton";
import { Providers } from "./providers";

const clash = localFont({
  src: [
    {
      path: "../../public/fonts/ClashDisplay-Variable.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/ClashDisplay-Variable.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/ClashDisplay-Variable.ttf",
      weight: "600",
    },
    {
      path: "../../public/fonts/ClashDisplay-Variable.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/ClashDisplay-Variable.ttf",
      weight: "900",
    },
  ],
  variable: "--font-clash",
});

// const roboto = Roboto({
//   weight: "400",
//   subsets: ["latin"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Ui Fry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <html lang="en" suppressHydrationWarning> */}
      <body className={`${clash.variable}`}>
        <div className="px-10 font-clash ">
          <Providers>
            <NavBar />
            {children}
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
